sudo: required
services:
  - docker

before_install:
  - docker build -t alexskinner/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexskinner/react-test npm test -- --coverage

after_success:
  - docker build -t alexskinner/multi-client ./client
  - docker build -t alexskinner/multi-nginx ./nginx
  - docker build -t alexskinner/multi-server ./server
  - docker build -t alexskinner/multi-worker ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push alexskinner/multi-client
  - docker push alexskinner/multi-nginx
  - docker push alexskinner/multi-server
  - docker push alexskinner/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "multi-docker2"
    env: "MultiDocker2-env"
    bucket_name: "elasticbeanstalk-eu-west-2-123571552574"
    bucket_path: "docker-multi"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"